// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_integral_sum
double compute_integral_sum(NumericVector x_vals, NumericVector y_vals);
RcppExport SEXP _SA24204159_compute_integral_sum(SEXP x_valsSEXP, SEXP y_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_vals(y_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_integral_sum(x_vals, y_vals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204159_compute_integral_sum", (DL_FUNC) &_SA24204159_compute_integral_sum, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204159(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
